#!/bin/bash
#SBATCH --nodes=1                           # node count
#SBATCH --ntasks=1                          # total number of tasks across all nodes
#SBATCH --cpus-per-task=1                   # cpu-cores per task (>1 if multi-threaded tasks), 4 is default
#SBATCH --gpus=1                            # number of gpus per node
#SBATCH --partition=gpu_a100                # partition
#SBATCH --time=30:00:00                     # total run time limit (HH:MM:SS)
#SBATCH --output=logs/TET/%A.log       # output file

source .venv/bin/activate
alias python=~/tea/.venv/bin/python

export WANDB_API_KEY="2148afe46d8dc6bca46f060d1665321d425917a6"

# select gpu 0
export CUDA_VISIBLE_DEVICES=0
# for debugging
# export CUDA_LAUNCH_BLOCKING=1

python train_TET_energy_scheduler.py --cfg cfgs/cifar100/pretrain_TET.yaml
